### ISSUE TITLE
Monitor internal state in BasicCartesianControl/CartesianControlServer

### ISSUE THREAD

**Issue by PeterBowman** [roboticslab-uc3m/kinematics-dynamics#118]
Some thoughts arised while working on the BCC/CCS at #117:

- [x] Forbid simultaneous execution of RPC and streaming commands. This is monitored via command presets (https://github.com/roboticslab-uc3m/kinematics-dynamics/commit/d2e79f5e3ff4b968afa4c25e2c311445f34b41d8).
- [x] Allow only one active connection for streaming commands (maybe RPC too)? Might be necessary to enforce this in the CartesianControlClient plugin. **Not doing**, this should be handled in the NWS/NWC layer and flexibility would be at risk if implemented, we could actually benefit from multiple CCS accessing `stat` or others. We do have some safety mechanisms in place, though, to guard against ugly race conditions.
- [x] Keep track of run/stop states to avoid frequent mode changes and reduce amount of messages sent to the real robot. (https://github.com/roboticslab-uc3m/kinematics-dynamics/commit/a597ef982fef700b9b2a28e850bc24b3511ecfb9)
- [x] Stop control if erroring at streaming commands (remember that these return no success/failure flag)? (https://github.com/roboticslab-uc3m/kinematics-dynamics/commit/82e87b6496ffa159fdaabc6330e47cd6bb1c4120)
- [x] Handle blocking/non-blocking operations (proposal: new `wait()` method, see #106).
- [x] Quit if connection with remote robot/simulator is lost? The CMC is aborted in case 20 consecutive encoder reads are not received. (https://github.com/roboticslab-uc3m/kinematics-dynamics/commit/1ab0339afa03fd1cfef37005d6654e28ce751654)
- [x] Make linear trajectories depend on velocity instead of time (#157). Not done as of 2022/07/13, see that issue for follow-ups.
- [x] Refuse setting controller parameters (`VOCAB_CC_CONFIG_XXX`) if not in non-controlling state (`stopControl()`). (https://github.com/roboticslab-uc3m/kinematics-dynamics/commit/6e78a535538298730670d53cd8206d504bc01a46, https://github.com/roboticslab-uc3m/kinematics-dynamics/commit/ac4e607219e7d68c1914b72ca4a44973d035c8cd)
- [x] Warn or stop control when limits are hit (https://github.com/roboticslab-uc3m/kinematics-dynamics/issues/161).
- [x] Allow concurrent requests for new movv commands, especially for the *keyboardController* app (https://github.com/roboticslab-uc3m/kinematics-dynamics/issues/166). (https://github.com/roboticslab-uc3m/kinematics-dynamics/commit/eae5bd1187444c135814b540a6e695acd331a966)
- [x] Move mode change out of each command? Example: `movi` performs that switch on its very first execution, but it takes quite long due to hardware limitations. **Idea:** preset control modes via controller configuration parameters iff using streaming commands. (https://github.com/roboticslab-uc3m/kinematics-dynamics/commit/852453def97f9cc1765fdc1d7ed7fc1242963cba)
- [x] Relax hard requirements on controlboard subdevices. For instance, AmorControlboard has no current implementation of IPositionDirect and this is only needed for issuing movi commands, but BCC would report an error on instantiation anyway. **Not doing** and not caring of AmorControlboard as of 2022 anymore. We have AmorCartesianControl instead. Besides, AmorControlboard should be repurposed as a collection of raw device instances in the vein of TechnosoftIpos, but again, it might be never done due to lack of interest.

**Comment by PeterBowman** [comment]
This issue was repurposed to focus solely on internal state considerations regarding the BasicCartesianControl implementation and its network wrapper (possibly spanning to AmorCartesianControl, too). Initial and on-runtime controller configuration will be discussed at #121.

**Comment by PeterBowman** [comment]
Regarding internal state and concurrency issues, check https://github.com/roboticslab-uc3m/kinematics-dynamics/pull/129#issuecomment-354472379. Conveniently pasted excerpt:

> * multi-threading within the controller itself (e.g. `RateThread`): current locks cover the state identifier (`getCurrentState`, `setCurrentState`), but some other members are shared between threads without mutex guards (e.g. desired cartesian velocities and forces); by now, we could assume that issuing multiple commands simultaneously is not allowed and re-think the internal behavior in #118 :question:

**Comment by PeterBowman** [comment]
Idea (from https://github.com/roboticslab-uc3m/kinematics-dynamics/issues/121#issuecomment-350555938): stream configuration parameters (#121) in the recently created `state:o` port.

**Comment by PeterBowman** [comment]
> Idea (from #121 (comment)): stream configuration parameters (#121) in the recently created state:o port.

Not sure about this, we'll rarely want to access config params in a high frequency manner. RPC set/get calls should be enough. The only advantage I see here is that `yarp rpc` access to the `stat` command will retrieve a comprehensive list of these parameters and their current value, but this would obviously render no benefits when querying the data programatically (i.e. via `CartesianControlClient`).

Another idea: provide a *bonus* RPC vocab to retrieve **all** config parameters with their value. For both interfaces:

* CLI (`yarp rpc`): simply list the values, similarly to `[help] [more]`
* C++ code: store keys and values in a `std::map`

**Comment by jgvictores** [comment]
> Not sure about this, we'll rarely want to access config params in a high frequency manner. RPC set/get calls should be enough. The only advantage I see here is that yarp rpc access to the stat command will retrieve a comprehensive list of these parameters and their current value, but this would obviously render no benefits when querying the data programatically (i.e. via CartesianControlClient).

I agree.

> CLI (yarp rpc): simply list the values, similarly to [help] [more]
> C++ code: store keys and values in a std::map

Cool. For `yarp rpc`, something like `[get] [prms]` sounds good to me!

**Comment by PeterBowman** [comment]
Added reference to related issue in description: #106.

**Comment by PeterBowman** [comment]
In spite of 7d2e073, I'd like to decouple our internal vocabs from those used by YARP controlboard interfaces (which have nothing to do with cartesian control). @jgvictores OK to create `VOCAB_CC_OK`, `VOCAB_CC_FAILED`, `VOCAB_CC_SET` and `VOCAB_CC_GET`? They would resolve to the values users are already familiar with (`[ok]`, `[fail]`, `[set]`, `[get]`, respectively).

**Comment by jgvictores** [comment]
> OK to create `VOCAB_CC_OK`, `VOCAB_CC_FAILED`, `VOCAB_CC_SET` and `VOCAB_CC_GET`? They would resolve to the values users are already familiar with (`[ok]`, `[fail]`, `[set]`, `[get]`, respectively).

Sure!

**Comment by PeterBowman** [comment]
New vocab definitions and group parameter accessors: https://github.com/roboticslab-uc3m/kinematics-dynamics/issues/121#issuecomment-359628756.

**Comment by PeterBowman** [comment]
Keyword: **state machines** (FSM). Several checks should be performed against internal state variables upon entering most of the control commands (e.g. current control mode, whether the trajectory instance is cleared and ready for use, etc.). The CMC thread would take care of any necessary cleanup before and after execution.

**Comment by PeterBowman** [comment]
For now, marking as blocked by #145.

**Comment by PeterBowman** [comment]
Added to list: refuse setting controller parameters (`VOCAB_CC_CONFIG_XXX`) if not in non-controlling state (`stopControl()`).

**Comment by PeterBowman** [comment]
Moving this away from the issue description regarding control modes:

> See the following excerpt from `BasicCartesianControl::stopControl`:
> https://github.com/roboticslab-uc3m/kinematics-dynamics/blob/37571fa1329c89ad77bd5b52255b2bfc558332c6/libraries/TeoYarp/BasicCartesianControl/ICartesianControlImpl.cpp#L243-L248
> Perhaps we can solve it upstream (that is, in the robot controller), see roboticslab-uc3m/yarp-devices#120).

**Comment by PeterBowman** [comment]
Regarding locks and race conditions because of port callbacks being invoked at the same time, see [`yarp::os::Contactable::lockCallback`](http://www.yarp.it/classyarp_1_1os_1_1Contactable.html#a53c6446cec1b3cf84ee2e5d636fb4d45) and other lock-related methods. Also: https://github.com/robotology/QA/issues/188 and the [*ex0300_port_callback* example](https://github.com/robotology/yarp/blob/14fef1096f9ab944df2227953097e3f164fe913c/example/port_power/ex0300_port_callback.cpp).
